FROM lovato/python-2.6.6
MAINTAINER Autodesk <info@autodesk.com>

#RUN apt-get install -y python-pip
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y python-nose
COPY . /app
RUN cp /app/tests/example_config /app/config

WORKDIR /app