"""Dummy data returned for schema functions when mocking the server.

NOTE: Mostly abbreviated version of real data returned from the server. 
"""

schema_entity_read = {'Version': {'name': {'editable': False, 'value': 'Version'}}}

schema_read = {
    'Version' : {'code': {'data_type': {'editable': False, 'value': 'text'},
           'description': {'editable': True, 'value': ''},
           'editable': {'editable': False, 'value': True},
           'entity_type': {'editable': False, 'value': 'Version'},
           'mandatory': {'editable': False, 'value': True},
           'name': {'editable': True, 'value': 'Version Name'},
           'properties': {'default_value': {'editable': False,
                                              'value': None},
                           'summary_default': {'editable': True,
                                                'value': 'none'}}},
 'created_at': {'data_type': {'editable': False, 'value': 'date_time'},
                 'description': {'editable': True, 'value': ''},
                 'editable': {'editable': False, 'value': False},
                 'entity_type': {'editable': False, 'value': 'Version'},
                 'mandatory': {'editable': False, 'value': False},
                 'name': {'editable': True, 'value': 'Date Created'},
                 'properties': {'default_value': {'editable': False,
                                                    'value': None},
                                 'summary_default': {'editable': True,
                                                      'value': 'none'}}},
 'created_by': {'data_type': {'editable': False, 'value': 'entity'},
                 'description': {'editable': True, 'value': ''},
                 'editable': {'editable': False, 'value': False},
                 'entity_type': {'editable': False, 'value': 'Version'},
                 'mandatory': {'editable': False, 'value': False},
                 'name': {'editable': True, 'value': 'Created by'},
                 'properties': {'default_value': {'editable': False,
                                                    'value': None},
                                 'summary_default': {'editable': True,
                                                      'value': 'none'},
                                 'valid_types': {'editable': True,
                                                  'value': ['HumanUser',
                                                             'ApiUser']}}},
 'description': {'data_type': {'editable': False, 'value': 'text'},
                  'description': {'editable': True, 'value': ''},
                  'editable': {'editable': False, 'value': True},
                  'entity_type': {'editable': False, 'value': 'Version'},
                  'mandatory': {'editable': False, 'value': False},
                  'name': {'editable': True, 'value': 'Description'},
                  'properties': {'default_value': {'editable': False,
                                                     'value': None},
                                  'summary_default': {'editable': True,
                                                       'value': 'none'}}},
 'entity': {'data_type': {'editable': False, 'value': 'entity'},
             'description': {'editable': True, 'value': ''},
             'editable': {'editable': False, 'value': True},
             'entity_type': {'editable': False, 'value': 'Version'},
             'mandatory': {'editable': False, 'value': False},
             'name': {'editable': True, 'value': 'Link'},
             'properties': {'default_value': {'editable': False,
                                                'value': None},
                             'summary_default': {'editable': True,
                                                  'value': 'none'},
                             'valid_types': {'editable': True,
                                              'value': ['Asset',
                                                         'Scene',
                                                         'Sequence',
                                                         'Shot']}}},
 'frame_count': {'data_type': {'editable': False, 'value': 'number'},
                  'description': {'editable': True, 'value': ''},
                  'editable': {'editable': False, 'value': True},
                  'entity_type': {'editable': False, 'value': 'Version'},
                  'mandatory': {'editable': False, 'value': False},
                  'name': {'editable': True, 'value': 'Frame Count'},
                  'properties': {'default_value': {'editable': False,
                                                     'value': None},
                                  'summary_default': {'editable': True,
                                                       'value': 'none'}}},
 'frame_range': {'data_type': {'editable': False, 'value': 'text'},
                  'description': {'editable': True, 'value': ''},
                  'editable': {'editable': False, 'value': True},
                  'entity_type': {'editable': False, 'value': 'Version'},
                  'mandatory': {'editable': False, 'value': False},
                  'name': {'editable': True, 'value': 'Frame Range'},
                  'properties': {'default_value': {'editable': False,
                                                     'value': None},
                                  'summary_default': {'editable': True,
                                                       'value': 'none'}}},
 'id': {'data_type': {'editable': False, 'value': 'number'},
         'description': {'editable': True, 'value': ''},
         'editable': {'editable': False, 'value': False},
         'entity_type': {'editable': False, 'value': 'Version'},
         'mandatory': {'editable': False, 'value': False},
         'name': {'editable': True, 'value': 'Id'},
         'properties': {'default_value': {'editable': False,
                                            'value': None},
                         'summary_default': {'editable': True,
                                              'value': 'none'}}},
 'image': {'data_type': {'editable': False, 'value': 'image'},
            'description': {'editable': True, 'value': ''},
            'editable': {'editable': False, 'value': True},
            'entity_type': {'editable': False, 'value': 'Version'},
            'mandatory': {'editable': False, 'value': False},
            'name': {'editable': True, 'value': 'Thumbnail'},
            'properties': {'default_value': {'editable': False,
                                               'value': None},
                            'summary_default': {'editable': True,
                                                 'value': 'none'}}},
 'notes': {'data_type': {'editable': False, 'value': 'multi_entity'},
            'description': {'editable': True, 'value': ''},
            'editable': {'editable': False, 'value': True},
            'entity_type': {'editable': False, 'value': 'Version'},
            'mandatory': {'editable': False, 'value': False},
            'name': {'editable': True, 'value': 'Notes'},
            'properties': {'default_value': {'editable': False,
                                               'value': None},
                            'summary_default': {'editable': True,
                                                 'value': 'none'},
                            'valid_types': {'editable': True,
                                             'value': ['Note']}}},
 'open_notes': {'data_type': {'editable': False,
                                'value': 'multi_entity'},
                 'description': {'editable': True, 'value': ''},
                 'editable': {'editable': False, 'value': False},
                 'entity_type': {'editable': False, 'value': 'Version'},
                 'mandatory': {'editable': False, 'value': False},
                 'name': {'editable': True, 'value': 'Open Notes'},
                 'properties': {'default_value': {'editable': False,
                                                    'value': None},
                                 'summary_default': {'editable': True,
                                                      'value': 'none'},
                                 'valid_types': {'editable': True,
                                                  'value': ['Note']}}},
 'open_notes_count': {'data_type': {'editable': False, 'value': 'text'},
                       'description': {'editable': True, 'value': ''},
                       'editable': {'editable': False, 'value': False},
                       'entity_type': {'editable': False,
                                        'value': 'Version'},
                       'mandatory': {'editable': False, 'value': False},
                       'name': {'editable': True,
                                 'value': 'Open Notes Count'},
                       'properties': {'default_value': {'editable': False,
                                                          'value': None},
                                       'summary_default': {'editable': True,
                                                            'value': 'none'}}},
 'playlists': {'data_type': {'editable': False, 'value': 'multi_entity'},
                'description': {'editable': True, 'value': ''},
                'editable': {'editable': False, 'value': True},
                'entity_type': {'editable': False, 'value': 'Version'},
                'mandatory': {'editable': False, 'value': False},
                'name': {'editable': True, 'value': 'Playlists'},
                'properties': {'default_value': {'editable': False,
                                                   'value': None},
                                'summary_default': {'editable': True,
                                                     'value': 'none'},
                                'valid_types': {'editable': True,
                                                 'value': ['Playlist']}}},
 'project': {'data_type': {'editable': False, 'value': 'entity'},
              'description': {'editable': True, 'value': ''},
              'editable': {'editable': False, 'value': True},
              'entity_type': {'editable': False, 'value': 'Version'},
              'mandatory': {'editable': False, 'value': False},
              'name': {'editable': True, 'value': 'Project'},
              'properties': {'default_value': {'editable': False,
                                                 'value': None},
                              'summary_default': {'editable': True,
                                                   'value': 'none'},
                              'valid_types': {'editable': True,
                                               'value': ['Project']}}},
 'sg_department': {'data_type': {'editable': False, 'value': 'text'},
                    'description': {'editable': True,
                                     'value': 'The department the Version was submitted from. This is used to find the latest Version from the same department.'},
                    'editable': {'editable': False, 'value': True},
                    'entity_type': {'editable': False,
                                     'value': 'Version'},
                    'mandatory': {'editable': False, 'value': False},
                    'name': {'editable': True, 'value': 'Department'},
                    'properties': {'default_value': {'editable': False,
                                                       'value': None},
                                    'summary_default': {'editable': True,
                                                         'value': 'none'}}},
 'sg_first_frame': {'data_type': {'editable': False, 'value': 'number'},
                     'description': {'editable': True,
                                      'value': 'The first frame number contained in the Version. Used in playback of the movie or frames to calculate the first frame available in the Version.'},
                     'editable': {'editable': False, 'value': True},
                     'entity_type': {'editable': False,
                                      'value': 'Version'},
                     'mandatory': {'editable': False, 'value': False},
                     'name': {'editable': True, 'value': 'First Frame'},
                     'properties': {'default_value': {'editable': False,
                                                        'value': None},
                                     'summary_default': {'editable': True,
                                                          'value': 'none'}}},
 'sg_frames_aspect_ratio': {'data_type': {'editable': False,
                                            'value': 'float'},
                             'description': {'editable': True,
                                              'value': 'Aspect ratio of the high res frames. Used to format the image correctly for viewing.'},
                             'editable': {'editable': False,
                                           'value': True},
                             'entity_type': {'editable': False,
                                              'value': 'Version'},
                             'mandatory': {'editable': False,
                                            'value': False},
                             'name': {'editable': True,
                                       'value': 'Frames Aspect Ratio'},
                             'properties': {'default_value': {'editable': False,
                                                                'value': None},
                                             'summary_default': {'editable': True,
                                                                  'value': 'none'}}},
 'sg_frames_have_slate': {'data_type': {'editable': False,
                                          'value': 'checkbox'},
                           'description': {'editable': True,
                                            'value': 'Indicates whether the frames have a slate or not. This is used to include or omit the slate from playback.'},
                           'editable': {'editable': False, 'value': True},
                           'entity_type': {'editable': False,
                                            'value': 'Version'},
                           'mandatory': {'editable': False,
                                          'value': False},
                           'name': {'editable': True,
                                     'value': 'Frames Have Slate'},
                           'properties': {'default_value': {'editable': False,
                                                              'value': False},
                                           'summary_default': {'editable': True,
                                                                'value': 'none'}}},
 'sg_last_frame': {'data_type': {'editable': False, 'value': 'number'},
                    'description': {'editable': True,
                                     'value': 'The last frame number contained in the Version. Used in playback of the movie or frames to calculate the last frame available in the Version.'},
                    'editable': {'editable': False, 'value': True},
                    'entity_type': {'editable': False,
                                     'value': 'Version'},
                    'mandatory': {'editable': False, 'value': False},
                    'name': {'editable': True, 'value': 'Last Frame'},
                    'properties': {'default_value': {'editable': False,
                                                       'value': None},
                                    'summary_default': {'editable': True,
                                                         'value': 'none'}}},
 'sg_movie_aspect_ratio': {'data_type': {'editable': False,
                                           'value': 'float'},
                            'description': {'editable': True,
                                             'value': 'Aspect ratio of the the movie. Used to format the image correctly for viewing.'},
                            'editable': {'editable': False, 'value': True},
                            'entity_type': {'editable': False,
                                             'value': 'Version'},
                            'mandatory': {'editable': False,
                                           'value': False},
                            'name': {'editable': True,
                                      'value': 'Movie Aspect Ratio'},
                            'properties': {'default_value': {'editable': False,
                                                               'value': None},
                                            'summary_default': {'editable': True,
                                                                 'value': 'none'}}},
 'sg_movie_has_slate': {'data_type': {'editable': False,
                                        'value': 'checkbox'},
                         'description': {'editable': True,
                                          'value': 'Indicates whether the movie file has a slate or not. This is used to include or omit the slate from playback.'},
                         'editable': {'editable': False, 'value': True},
                         'entity_type': {'editable': False,
                                          'value': 'Version'},
                         'mandatory': {'editable': False, 'value': False},
                         'name': {'editable': True,
                                   'value': 'Movie Has Slate'},
                         'properties': {'default_value': {'editable': False,
                                                            'value': False},
                                         'summary_default': {'editable': True,
                                                              'value': 'none'}}},
 'sg_path_to_frames': {'data_type': {'editable': False, 'value': 'text'},
                        'description': {'editable': True,
                                         'value': 'Location of the high res frames on your local filesystem. Used for playback of high resolution frames.'},
                        'editable': {'editable': False, 'value': True},
                        'entity_type': {'editable': False,
                                         'value': 'Version'},
                        'mandatory': {'editable': False, 'value': False},
                        'name': {'editable': True,
                                  'value': 'Path to Frames'},
                        'properties': {'default_value': {'editable': False,
                                                           'value': None},
                                        'summary_default': {'editable': True,
                                                             'value': 'none'}}},
 'sg_path_to_movie': {'data_type': {'editable': False, 'value': 'text'},
                       'description': {'editable': True,
                                        'value': 'Location of the movie on your local filesystem (not uploaded). Used for playback of lower resolution movie media stored locally.'},
                       'editable': {'editable': False, 'value': True},
                       'entity_type': {'editable': False,
                                        'value': 'Version'},
                       'mandatory': {'editable': False, 'value': False},
                       'name': {'editable': True,
                                 'value': 'Path to Movie'},
                       'properties': {'default_value': {'editable': False,
                                                          'value': None},
                                       'summary_default': {'editable': True,
                                                            'value': 'none'}}},
 'sg_status_list': {'data_type': {'editable': False,
                                    'value': 'status_list'},
                     'description': {'editable': True, 'value': ''},
                     'editable': {'editable': False, 'value': True},
                     'entity_type': {'editable': False,
                                      'value': 'Version'},
                     'mandatory': {'editable': False, 'value': False},
                     'name': {'editable': True, 'value': 'Status'},
                     'properties': {'default_value': {'editable': True,
                                                        'value': 'rev'},
                                     'summary_default': {'editable': True,
                                                          'value': 'status_list'},
                                     'valid_values': {'editable': True,
                                                       'value': ['na',
                                                                  'rev',
                                                                  'vwd']}}},
 'sg_task': {'data_type': {'editable': False, 'value': 'entity'},
              'description': {'editable': True, 'value': ''},
              'editable': {'editable': False, 'value': True},
              'entity_type': {'editable': False, 'value': 'Version'},
              'mandatory': {'editable': False, 'value': False},
              'name': {'editable': True, 'value': 'Task'},
              'properties': {'default_value': {'editable': False,
                                                 'value': None},
                              'summary_default': {'editable': True,
                                                   'value': 'none'},
                              'valid_types': {'editable': True,
                                               'value': ['Task']}}},
 'sg_uploaded_movie': {'data_type': {'editable': False, 'value': 'url'},
                        'description': {'editable': True,
                                         'value': 'File field to contain the uploaded movie file. Used for playback of lower resolution movie media stored in Shotgun.'},
                        'editable': {'editable': False, 'value': True},
                        'entity_type': {'editable': False,
                                         'value': 'Version'},
                        'mandatory': {'editable': False, 'value': False},
                        'name': {'editable': True,
                                  'value': 'Uploaded Movie'},
                        'properties': {'default_value': {'editable': False,
                                                           'value': None},
                                        'open_in_new_window': {'editable': True,
                                                                'value': True},
                                        'summary_default': {'editable': True,
                                                             'value': 'none'}}},
 'sg_version_type': {'data_type': {'editable': False, 'value': 'list'},
                      'description': {'editable': True, 'value': ''},
                      'editable': {'editable': False, 'value': True},
                      'entity_type': {'editable': False,
                                       'value': 'Version'},
                      'mandatory': {'editable': False, 'value': False},
                      'name': {'editable': True, 'value': 'Type'},
                      'properties': {'default_value': {'editable': False,
                                                         'value': None},
                                      'summary_default': {'editable': True,
                                                           'value': 'none'},
                                      'valid_values': {'editable': True,
                                                        'value': []}}},
 'step_0': {'data_type': {'editable': False, 'value': 'pivot_column'},
             'description': {'editable': True, 'value': ''},
             'editable': {'editable': False, 'value': False},
             'entity_type': {'editable': False, 'value': 'Version'},
             'mandatory': {'editable': False, 'value': False},
             'name': {'editable': True, 'value': 'ALL TASKS'},
             'properties': {'default_value': {'editable': False,
                                                'value': None},
                             'summary_default': {'editable': False,
                                                  'value': 'none'}}},
 'tag_list': {'data_type': {'editable': False, 'value': 'tag_list'},
               'description': {'editable': True, 'value': ''},
               'editable': {'editable': False, 'value': True},
               'entity_type': {'editable': False, 'value': 'Version'},
               'mandatory': {'editable': False, 'value': False},
               'name': {'editable': True, 'value': 'Tags'},
               'properties': {'default_value': {'editable': False,
                                                  'value': None},
                               'summary_default': {'editable': True,
                                                    'value': 'none'},
                               'valid_types': {'editable': True,
                                                'value': ['Tag']}}},
 'task_template': {'data_type': {'editable': False, 'value': 'entity'},
                    'description': {'editable': True, 'value': ''},
                    'editable': {'editable': False, 'value': True},
                    'entity_type': {'editable': False,
                                     'value': 'Version'},
                    'mandatory': {'editable': False, 'value': False},
                    'name': {'editable': True, 'value': 'Task Template'},
                    'properties': {'default_value': {'editable': False,
                                                       'value': None},
                                    'summary_default': {'editable': True,
                                                         'value': 'none'},
                                    'valid_types': {'editable': True,
                                                     'value': ['TaskTemplate']}}},
 'tasks': {'data_type': {'editable': False, 'value': 'multi_entity'},
            'description': {'editable': True, 'value': ''},
            'editable': {'editable': False, 'value': True},
            'entity_type': {'editable': False, 'value': 'Version'},
            'mandatory': {'editable': False, 'value': False},
            'name': {'editable': True, 'value': 'Tasks'},
            'properties': {'default_value': {'editable': False,
                                               'value': None},
                            'summary_default': {'editable': True,
                                                 'value': 'none'},
                            'valid_types': {'editable': True,
                                             'value': ['Task']}}},
 'updated_at': {'data_type': {'editable': False, 'value': 'date_time'},
                 'description': {'editable': True, 'value': ''},
                 'editable': {'editable': False, 'value': False},
                 'entity_type': {'editable': False, 'value': 'Version'},
                 'mandatory': {'editable': False, 'value': False},
                 'name': {'editable': True, 'value': 'Date Updated'},
                 'properties': {'default_value': {'editable': False,
                                                    'value': None},
                                 'summary_default': {'editable': True,
                                                      'value': 'none'}}},
 'updated_by': {'data_type': {'editable': False, 'value': 'entity'},
                 'description': {'editable': True, 'value': ''},
                 'editable': {'editable': False, 'value': False},
                 'entity_type': {'editable': False, 'value': 'Version'},
                 'mandatory': {'editable': False, 'value': False},
                 'name': {'editable': True, 'value': 'Updated by'},
                 'properties': {'default_value': {'editable': False,
                                                    'value': None},
                                 'summary_default': {'editable': True,
                                                      'value': 'none'},
                                 'valid_types': {'editable': True,
                                                  'value': ['HumanUser',
                                                             'ApiUser']}}},
 'user': {'data_type': {'editable': False, 'value': 'entity'},
           'description': {'editable': True, 'value': ''},
           'editable': {'editable': False, 'value': True},
           'entity_type': {'editable': False, 'value': 'Version'},
           'mandatory': {'editable': False, 'value': False},
           'name': {'editable': True, 'value': 'Artist'},
           'properties': {'default_value': {'editable': False,
                                              'value': None},
                           'summary_default': {'editable': True,
                                                'value': 'none'},
                           'valid_types': {'editable': True,
                                            'value': ['HumanUser',
                                                       'ApiUser']}}}
}}








schema_field_read_version = {'code': {'data_type': {'editable': False, 'value': 'text'},
           'description': {'editable': True, 'value': ''},
           'editable': {'editable': False, 'value': True},
           'entity_type': {'editable': False, 'value': 'Version'},
           'mandatory': {'editable': False, 'value': True},
           'name': {'editable': True, 'value': 'Version Name'},
           'properties': {'default_value': {'editable': False,
                                              'value': None},
                           'summary_default': {'editable': True,
                                                'value': 'none'}}},
 'created_at': {'data_type': {'editable': False, 'value': 'date_time'},
                 'description': {'editable': True, 'value': ''},
                 'editable': {'editable': False, 'value': False},
                 'entity_type': {'editable': False, 'value': 'Version'},
                 'mandatory': {'editable': False, 'value': False},
                 'name': {'editable': True, 'value': 'Date Created'},
                 'properties': {'default_value': {'editable': False,
                                                    'value': None},
                                 'summary_default': {'editable': True,
                                                      'value': 'none'}}},
 'created_by': {'data_type': {'editable': False, 'value': 'entity'},
                 'description': {'editable': True, 'value': ''},
                 'editable': {'editable': False, 'value': False},
                 'entity_type': {'editable': False, 'value': 'Version'},
                 'mandatory': {'editable': False, 'value': False},
                 'name': {'editable': True, 'value': 'Created by'},
                 'properties': {'default_value': {'editable': False,
                                                    'value': None},
                                 'summary_default': {'editable': True,
                                                      'value': 'none'},
                                 'valid_types': {'editable': True,
                                                  'value': ['HumanUser',
                                                             'ApiUser']}}},
 'description': {'data_type': {'editable': False, 'value': 'text'},
                  'description': {'editable': True, 'value': ''},
                  'editable': {'editable': False, 'value': True},
                  'entity_type': {'editable': False, 'value': 'Version'},
                  'mandatory': {'editable': False, 'value': False},
                  'name': {'editable': True, 'value': 'Description'},
                  'properties': {'default_value': {'editable': False,
                                                     'value': None},
                                  'summary_default': {'editable': True,
                                                       'value': 'none'}}},
 'entity': {'data_type': {'editable': False, 'value': 'entity'},
             'description': {'editable': True, 'value': ''},
             'editable': {'editable': False, 'value': True},
             'entity_type': {'editable': False, 'value': 'Version'},
             'mandatory': {'editable': False, 'value': False},
             'name': {'editable': True, 'value': 'Link'},
             'properties': {'default_value': {'editable': False,
                                                'value': None},
                             'summary_default': {'editable': True,
                                                  'value': 'none'},
                             'valid_types': {'editable': True,
                                              'value': ['Asset',
                                                         'Scene',
                                                         'Sequence',
                                                         'Shot']}}},
 'frame_count': {'data_type': {'editable': False, 'value': 'number'},
                  'description': {'editable': True, 'value': ''},
                  'editable': {'editable': False, 'value': True},
                  'entity_type': {'editable': False, 'value': 'Version'},
                  'mandatory': {'editable': False, 'value': False},
                  'name': {'editable': True, 'value': 'Frame Count'},
                  'properties': {'default_value': {'editable': False,
                                                     'value': None},
                                  'summary_default': {'editable': True,
                                                       'value': 'none'}}},
 'frame_range': {'data_type': {'editable': False, 'value': 'text'},
                  'description': {'editable': True, 'value': ''},
                  'editable': {'editable': False, 'value': True},
                  'entity_type': {'editable': False, 'value': 'Version'},
                  'mandatory': {'editable': False, 'value': False},
                  'name': {'editable': True, 'value': 'Frame Range'},
                  'properties': {'default_value': {'editable': False,
                                                     'value': None},
                                  'summary_default': {'editable': True,
                                                       'value': 'none'}}},
 'id': {'data_type': {'editable': False, 'value': 'number'},
         'description': {'editable': True, 'value': ''},
         'editable': {'editable': False, 'value': False},
         'entity_type': {'editable': False, 'value': 'Version'},
         'mandatory': {'editable': False, 'value': False},
         'name': {'editable': True, 'value': 'Id'},
         'properties': {'default_value': {'editable': False,
                                            'value': None},
                         'summary_default': {'editable': True,
                                              'value': 'none'}}},
 'image': {'data_type': {'editable': False, 'value': 'image'},
            'description': {'editable': True, 'value': ''},
            'editable': {'editable': False, 'value': True},
            'entity_type': {'editable': False, 'value': 'Version'},
            'mandatory': {'editable': False, 'value': False},
            'name': {'editable': True, 'value': 'Thumbnail'},
            'properties': {'default_value': {'editable': False,
                                               'value': None},
                            'summary_default': {'editable': True,
                                                 'value': 'none'}}},
 'notes': {'data_type': {'editable': False, 'value': 'multi_entity'},
            'description': {'editable': True, 'value': ''},
            'editable': {'editable': False, 'value': True},
            'entity_type': {'editable': False, 'value': 'Version'},
            'mandatory': {'editable': False, 'value': False},
            'name': {'editable': True, 'value': 'Notes'},
            'properties': {'default_value': {'editable': False,
                                               'value': None},
                            'summary_default': {'editable': True,
                                                 'value': 'none'},
                            'valid_types': {'editable': True,
                                             'value': ['Note']}}},
 'open_notes': {'data_type': {'editable': False,
                                'value': 'multi_entity'},
                 'description': {'editable': True, 'value': ''},
                 'editable': {'editable': False, 'value': False},
                 'entity_type': {'editable': False, 'value': 'Version'},
                 'mandatory': {'editable': False, 'value': False},
                 'name': {'editable': True, 'value': 'Open Notes'},
                 'properties': {'default_value': {'editable': False,
                                                    'value': None},
                                 'summary_default': {'editable': True,
                                                      'value': 'none'},
                                 'valid_types': {'editable': True,
                                                  'value': ['Note']}}},
 'open_notes_count': {'data_type': {'editable': False, 'value': 'text'},
                       'description': {'editable': True, 'value': ''},
                       'editable': {'editable': False, 'value': False},
                       'entity_type': {'editable': False,
                                        'value': 'Version'},
                       'mandatory': {'editable': False, 'value': False},
                       'name': {'editable': True,
                                 'value': 'Open Notes Count'},
                       'properties': {'default_value': {'editable': False,
                                                          'value': None},
                                       'summary_default': {'editable': True,
                                                            'value': 'none'}}},
 'playlists': {'data_type': {'editable': False, 'value': 'multi_entity'},
                'description': {'editable': True, 'value': ''},
                'editable': {'editable': False, 'value': True},
                'entity_type': {'editable': False, 'value': 'Version'},
                'mandatory': {'editable': False, 'value': False},
                'name': {'editable': True, 'value': 'Playlists'},
                'properties': {'default_value': {'editable': False,
                                                   'value': None},
                                'summary_default': {'editable': True,
                                                     'value': 'none'},
                                'valid_types': {'editable': True,
                                                 'value': ['Playlist']}}},
 'project': {'data_type': {'editable': False, 'value': 'entity'},
              'description': {'editable': True, 'value': ''},
              'editable': {'editable': False, 'value': True},
              'entity_type': {'editable': False, 'value': 'Version'},
              'mandatory': {'editable': False, 'value': False},
              'name': {'editable': True, 'value': 'Project'},
              'properties': {'default_value': {'editable': False,
                                                 'value': None},
                              'summary_default': {'editable': True,
                                                   'value': 'none'},
                              'valid_types': {'editable': True,
                                               'value': ['Project']}}},
 'sg_department': {'data_type': {'editable': False, 'value': 'text'},
                    'description': {'editable': True,
                                     'value': 'The department the Version was submitted from. This is used to find the latest Version from the same department.'},
                    'editable': {'editable': False, 'value': True},
                    'entity_type': {'editable': False,
                                     'value': 'Version'},
                    'mandatory': {'editable': False, 'value': False},
                    'name': {'editable': True, 'value': 'Department'},
                    'properties': {'default_value': {'editable': False,
                                                       'value': None},
                                    'summary_default': {'editable': True,
                                                         'value': 'none'}}},
 'sg_first_frame': {'data_type': {'editable': False, 'value': 'number'},
                     'description': {'editable': True,
                                      'value': 'The first frame number contained in the Version. Used in playback of the movie or frames to calculate the first frame available in the Version.'},
                     'editable': {'editable': False, 'value': True},
                     'entity_type': {'editable': False,
                                      'value': 'Version'},
                     'mandatory': {'editable': False, 'value': False},
                     'name': {'editable': True, 'value': 'First Frame'},
                     'properties': {'default_value': {'editable': False,
                                                        'value': None},
                                     'summary_default': {'editable': True,
                                                          'value': 'none'}}},
 'sg_frames_aspect_ratio': {'data_type': {'editable': False,
                                            'value': 'float'},
                             'description': {'editable': True,
                                              'value': 'Aspect ratio of the high res frames. Used to format the image correctly for viewing.'},
                             'editable': {'editable': False,
                                           'value': True},
                             'entity_type': {'editable': False,
                                              'value': 'Version'},
                             'mandatory': {'editable': False,
                                            'value': False},
                             'name': {'editable': True,
                                       'value': 'Frames Aspect Ratio'},
                             'properties': {'default_value': {'editable': False,
                                                                'value': None},
                                             'summary_default': {'editable': True,
                                                                  'value': 'none'}}},
 'sg_frames_have_slate': {'data_type': {'editable': False,
                                          'value': 'checkbox'},
                           'description': {'editable': True,
                                            'value': 'Indicates whether the frames have a slate or not. This is used to include or omit the slate from playback.'},
                           'editable': {'editable': False, 'value': True},
                           'entity_type': {'editable': False,
                                            'value': 'Version'},
                           'mandatory': {'editable': False,
                                          'value': False},
                           'name': {'editable': True,
                                     'value': 'Frames Have Slate'},
                           'properties': {'default_value': {'editable': False,
                                                              'value': False},
                                           'summary_default': {'editable': True,
                                                                'value': 'none'}}},
 'sg_last_frame': {'data_type': {'editable': False, 'value': 'number'},
                    'description': {'editable': True,
                                     'value': 'The last frame number contained in the Version. Used in playback of the movie or frames to calculate the last frame available in the Version.'},
                    'editable': {'editable': False, 'value': True},
                    'entity_type': {'editable': False,
                                     'value': 'Version'},
                    'mandatory': {'editable': False, 'value': False},
                    'name': {'editable': True, 'value': 'Last Frame'},
                    'properties': {'default_value': {'editable': False,
                                                       'value': None},
                                    'summary_default': {'editable': True,
                                                         'value': 'none'}}},
 'sg_movie_aspect_ratio': {'data_type': {'editable': False,
                                           'value': 'float'},
                            'description': {'editable': True,
                                             'value': 'Aspect ratio of the the movie. Used to format the image correctly for viewing.'},
                            'editable': {'editable': False, 'value': True},
                            'entity_type': {'editable': False,
                                             'value': 'Version'},
                            'mandatory': {'editable': False,
                                           'value': False},
                            'name': {'editable': True,
                                      'value': 'Movie Aspect Ratio'},
                            'properties': {'default_value': {'editable': False,
                                                               'value': None},
                                            'summary_default': {'editable': True,
                                                                 'value': 'none'}}},
 'sg_movie_has_slate': {'data_type': {'editable': False,
                                        'value': 'checkbox'},
                         'description': {'editable': True,
                                          'value': 'Indicates whether the movie file has a slate or not. This is used to include or omit the slate from playback.'},
                         'editable': {'editable': False, 'value': True},
                         'entity_type': {'editable': False,
                                          'value': 'Version'},
                         'mandatory': {'editable': False, 'value': False},
                         'name': {'editable': True,
                                   'value': 'Movie Has Slate'},
                         'properties': {'default_value': {'editable': False,
                                                            'value': False},
                                         'summary_default': {'editable': True,
                                                              'value': 'none'}}},
 'sg_path_to_frames': {'data_type': {'editable': False, 'value': 'text'},
                        'description': {'editable': True,
                                         'value': 'Location of the high res frames on your local filesystem. Used for playback of high resolution frames.'},
                        'editable': {'editable': False, 'value': True},
                        'entity_type': {'editable': False,
                                         'value': 'Version'},
                        'mandatory': {'editable': False, 'value': False},
                        'name': {'editable': True,
                                  'value': 'Path to Frames'},
                        'properties': {'default_value': {'editable': False,
                                                           'value': None},
                                        'summary_default': {'editable': True,
                                                             'value': 'none'}}},
 'sg_path_to_movie': {'data_type': {'editable': False, 'value': 'text'},
                       'description': {'editable': True,
                                        'value': 'Location of the movie on your local filesystem (not uploaded). Used for playback of lower resolution movie media stored locally.'},
                       'editable': {'editable': False, 'value': True},
                       'entity_type': {'editable': False,
                                        'value': 'Version'},
                       'mandatory': {'editable': False, 'value': False},
                       'name': {'editable': True,
                                 'value': 'Path to Movie'},
                       'properties': {'default_value': {'editable': False,
                                                          'value': None},
                                       'summary_default': {'editable': True,
                                                            'value': 'none'}}},
 'sg_status_list': {'data_type': {'editable': False,
                                    'value': 'status_list'},
                     'description': {'editable': True, 'value': ''},
                     'editable': {'editable': False, 'value': True},
                     'entity_type': {'editable': False,
                                      'value': 'Version'},
                     'mandatory': {'editable': False, 'value': False},
                     'name': {'editable': True, 'value': 'Status'},
                     'properties': {'default_value': {'editable': True,
                                                        'value': 'rev'},
                                     'summary_default': {'editable': True,
                                                          'value': 'status_list'},
                                     'valid_values': {'editable': True,
                                                       'value': ['na',
                                                                  'rev',
                                                                  'vwd']}}},
 'sg_task': {'data_type': {'editable': False, 'value': 'entity'},
              'description': {'editable': True, 'value': ''},
              'editable': {'editable': False, 'value': True},
              'entity_type': {'editable': False, 'value': 'Version'},
              'mandatory': {'editable': False, 'value': False},
              'name': {'editable': True, 'value': 'Task'},
              'properties': {'default_value': {'editable': False,
                                                 'value': None},
                              'summary_default': {'editable': True,
                                                   'value': 'none'},
                              'valid_types': {'editable': True,
                                               'value': ['Task']}}},
 'sg_uploaded_movie': {'data_type': {'editable': False, 'value': 'url'},
                        'description': {'editable': True,
                                         'value': 'File field to contain the uploaded movie file. Used for playback of lower resolution movie media stored in Shotgun.'},
                        'editable': {'editable': False, 'value': True},
                        'entity_type': {'editable': False,
                                         'value': 'Version'},
                        'mandatory': {'editable': False, 'value': False},
                        'name': {'editable': True,
                                  'value': 'Uploaded Movie'},
                        'properties': {'default_value': {'editable': False,
                                                           'value': None},
                                        'open_in_new_window': {'editable': True,
                                                                'value': True},
                                        'summary_default': {'editable': True,
                                                             'value': 'none'}}},
 'sg_version_type': {'data_type': {'editable': False, 'value': 'list'},
                      'description': {'editable': True, 'value': ''},
                      'editable': {'editable': False, 'value': True},
                      'entity_type': {'editable': False,
                                       'value': 'Version'},
                      'mandatory': {'editable': False, 'value': False},
                      'name': {'editable': True, 'value': 'Type'},
                      'properties': {'default_value': {'editable': False,
                                                         'value': None},
                                      'summary_default': {'editable': True,
                                                           'value': 'none'},
                                      'valid_values': {'editable': True,
                                                        'value': []}}},
 'step_0': {'data_type': {'editable': False, 'value': 'pivot_column'},
             'description': {'editable': True, 'value': ''},
             'editable': {'editable': False, 'value': False},
             'entity_type': {'editable': False, 'value': 'Version'},
             'mandatory': {'editable': False, 'value': False},
             'name': {'editable': True, 'value': 'ALL TASKS'},
             'properties': {'default_value': {'editable': False,
                                                'value': None},
                             'summary_default': {'editable': False,
                                                  'value': 'none'}}},
 'tag_list': {'data_type': {'editable': False, 'value': 'tag_list'},
               'description': {'editable': True, 'value': ''},
               'editable': {'editable': False, 'value': True},
               'entity_type': {'editable': False, 'value': 'Version'},
               'mandatory': {'editable': False, 'value': False},
               'name': {'editable': True, 'value': 'Tags'},
               'properties': {'default_value': {'editable': False,
                                                  'value': None},
                               'summary_default': {'editable': True,
                                                    'value': 'none'},
                               'valid_types': {'editable': True,
                                                'value': ['Tag']}}},
 'task_template': {'data_type': {'editable': False, 'value': 'entity'},
                    'description': {'editable': True, 'value': ''},
                    'editable': {'editable': False, 'value': True},
                    'entity_type': {'editable': False,
                                     'value': 'Version'},
                    'mandatory': {'editable': False, 'value': False},
                    'name': {'editable': True, 'value': 'Task Template'},
                    'properties': {'default_value': {'editable': False,
                                                       'value': None},
                                    'summary_default': {'editable': True,
                                                         'value': 'none'},
                                    'valid_types': {'editable': True,
                                                     'value': ['TaskTemplate']}}},
 'tasks': {'data_type': {'editable': False, 'value': 'multi_entity'},
            'description': {'editable': True, 'value': ''},
            'editable': {'editable': False, 'value': True},
            'entity_type': {'editable': False, 'value': 'Version'},
            'mandatory': {'editable': False, 'value': False},
            'name': {'editable': True, 'value': 'Tasks'},
            'properties': {'default_value': {'editable': False,
                                               'value': None},
                            'summary_default': {'editable': True,
                                                 'value': 'none'},
                            'valid_types': {'editable': True,
                                             'value': ['Task']}}},
 'updated_at': {'data_type': {'editable': False, 'value': 'date_time'},
                 'description': {'editable': True, 'value': ''},
                 'editable': {'editable': False, 'value': False},
                 'entity_type': {'editable': False, 'value': 'Version'},
                 'mandatory': {'editable': False, 'value': False},
                 'name': {'editable': True, 'value': 'Date Updated'},
                 'properties': {'default_value': {'editable': False,
                                                    'value': None},
                                 'summary_default': {'editable': True,
                                                      'value': 'none'}}},
 'updated_by': {'data_type': {'editable': False, 'value': 'entity'},
                 'description': {'editable': True, 'value': ''},
                 'editable': {'editable': False, 'value': False},
                 'entity_type': {'editable': False, 'value': 'Version'},
                 'mandatory': {'editable': False, 'value': False},
                 'name': {'editable': True, 'value': 'Updated by'},
                 'properties': {'default_value': {'editable': False,
                                                    'value': None},
                                 'summary_default': {'editable': True,
                                                      'value': 'none'},
                                 'valid_types': {'editable': True,
                                                  'value': ['HumanUser',
                                                             'ApiUser']}}},
 'user': {'data_type': {'editable': False, 'value': 'entity'},
           'description': {'editable': True, 'value': ''},
           'editable': {'editable': False, 'value': True},
           'entity_type': {'editable': False, 'value': 'Version'},
           'mandatory': {'editable': False, 'value': False},
           'name': {'editable': True, 'value': 'Artist'},
           'properties': {'default_value': {'editable': False,
                                              'value': None},
                           'summary_default': {'editable': True,
                                                'value': 'none'},
                           'valid_types': {'editable': True,
                                            'value': ['HumanUser',
                                                       'ApiUser']}}}}





schema_field_read_version_user = {'user': {'data_type': {'editable': False, 'value': 'entity'},
           'description': {'editable': True, 'value': ''},
           'editable': {'editable': False, 'value': True},
           'entity_type': {'editable': False, 'value': 'Version'},
           'mandatory': {'editable': False, 'value': False},
           'name': {'editable': True, 'value': 'Artist'},
           'properties': {'default_value': {'editable': False,
                                              'value': None},
                           'summary_default': {'editable': True,
                                                'value': 'none'},
                           'valid_types': {'editable': True,
                                            'value': ['HumanUser',
                                                       'ApiUser']}}}}
                                                       