"""Dummy data returned for schema functions when mocking the server.

NOTE: Mostly abbreviated version of real data returned from the server. 
"""

schema_entity_read = {u'Version': {u'name': {u'editable': False, u'value': u'Version'}}}

schema_read = {
    u'Version' : {u'code': {u'data_type': {u'editable': False, u'value': u'text'},
           u'description': {u'editable': True, u'value': u''},
           u'editable': {u'editable': False, u'value': True},
           u'entity_type': {u'editable': False, u'value': u'Version'},
           u'mandatory': {u'editable': False, u'value': True},
           u'name': {u'editable': True, u'value': u'Version Name'},
           u'properties': {u'default_value': {u'editable': False,
                                              u'value': None},
                           u'summary_default': {u'editable': True,
                                                u'value': u'none'}}},
 u'created_at': {u'data_type': {u'editable': False, u'value': u'date_time'},
                 u'description': {u'editable': True, u'value': u''},
                 u'editable': {u'editable': False, u'value': False},
                 u'entity_type': {u'editable': False, u'value': u'Version'},
                 u'mandatory': {u'editable': False, u'value': False},
                 u'name': {u'editable': True, u'value': u'Date Created'},
                 u'properties': {u'default_value': {u'editable': False,
                                                    u'value': None},
                                 u'summary_default': {u'editable': True,
                                                      u'value': u'none'}}},
 u'created_by': {u'data_type': {u'editable': False, u'value': u'entity'},
                 u'description': {u'editable': True, u'value': u''},
                 u'editable': {u'editable': False, u'value': False},
                 u'entity_type': {u'editable': False, u'value': u'Version'},
                 u'mandatory': {u'editable': False, u'value': False},
                 u'name': {u'editable': True, u'value': u'Created by'},
                 u'properties': {u'default_value': {u'editable': False,
                                                    u'value': None},
                                 u'summary_default': {u'editable': True,
                                                      u'value': u'none'},
                                 u'valid_types': {u'editable': True,
                                                  u'value': [u'HumanUser',
                                                             u'ApiUser']}}},
 u'description': {u'data_type': {u'editable': False, u'value': u'text'},
                  u'description': {u'editable': True, u'value': u''},
                  u'editable': {u'editable': False, u'value': True},
                  u'entity_type': {u'editable': False, u'value': u'Version'},
                  u'mandatory': {u'editable': False, u'value': False},
                  u'name': {u'editable': True, u'value': u'Description'},
                  u'properties': {u'default_value': {u'editable': False,
                                                     u'value': None},
                                  u'summary_default': {u'editable': True,
                                                       u'value': u'none'}}},
 u'entity': {u'data_type': {u'editable': False, u'value': u'entity'},
             u'description': {u'editable': True, u'value': u''},
             u'editable': {u'editable': False, u'value': True},
             u'entity_type': {u'editable': False, u'value': u'Version'},
             u'mandatory': {u'editable': False, u'value': False},
             u'name': {u'editable': True, u'value': u'Link'},
             u'properties': {u'default_value': {u'editable': False,
                                                u'value': None},
                             u'summary_default': {u'editable': True,
                                                  u'value': u'none'},
                             u'valid_types': {u'editable': True,
                                              u'value': [u'Asset',
                                                         u'Scene',
                                                         u'Sequence',
                                                         u'Shot']}}},
 u'frame_count': {u'data_type': {u'editable': False, u'value': u'number'},
                  u'description': {u'editable': True, u'value': u''},
                  u'editable': {u'editable': False, u'value': True},
                  u'entity_type': {u'editable': False, u'value': u'Version'},
                  u'mandatory': {u'editable': False, u'value': False},
                  u'name': {u'editable': True, u'value': u'Frame Count'},
                  u'properties': {u'default_value': {u'editable': False,
                                                     u'value': None},
                                  u'summary_default': {u'editable': True,
                                                       u'value': u'none'}}},
 u'frame_range': {u'data_type': {u'editable': False, u'value': u'text'},
                  u'description': {u'editable': True, u'value': u''},
                  u'editable': {u'editable': False, u'value': True},
                  u'entity_type': {u'editable': False, u'value': u'Version'},
                  u'mandatory': {u'editable': False, u'value': False},
                  u'name': {u'editable': True, u'value': u'Frame Range'},
                  u'properties': {u'default_value': {u'editable': False,
                                                     u'value': None},
                                  u'summary_default': {u'editable': True,
                                                       u'value': u'none'}}},
 u'id': {u'data_type': {u'editable': False, u'value': u'number'},
         u'description': {u'editable': True, u'value': u''},
         u'editable': {u'editable': False, u'value': False},
         u'entity_type': {u'editable': False, u'value': u'Version'},
         u'mandatory': {u'editable': False, u'value': False},
         u'name': {u'editable': True, u'value': u'Id'},
         u'properties': {u'default_value': {u'editable': False,
                                            u'value': None},
                         u'summary_default': {u'editable': True,
                                              u'value': u'none'}}},
 u'image': {u'data_type': {u'editable': False, u'value': u'image'},
            u'description': {u'editable': True, u'value': u''},
            u'editable': {u'editable': False, u'value': True},
            u'entity_type': {u'editable': False, u'value': u'Version'},
            u'mandatory': {u'editable': False, u'value': False},
            u'name': {u'editable': True, u'value': u'Thumbnail'},
            u'properties': {u'default_value': {u'editable': False,
                                               u'value': None},
                            u'summary_default': {u'editable': True,
                                                 u'value': u'none'}}},
 u'notes': {u'data_type': {u'editable': False, u'value': u'multi_entity'},
            u'description': {u'editable': True, u'value': u''},
            u'editable': {u'editable': False, u'value': True},
            u'entity_type': {u'editable': False, u'value': u'Version'},
            u'mandatory': {u'editable': False, u'value': False},
            u'name': {u'editable': True, u'value': u'Notes'},
            u'properties': {u'default_value': {u'editable': False,
                                               u'value': None},
                            u'summary_default': {u'editable': True,
                                                 u'value': u'none'},
                            u'valid_types': {u'editable': True,
                                             u'value': [u'Note']}}},
 u'open_notes': {u'data_type': {u'editable': False,
                                u'value': u'multi_entity'},
                 u'description': {u'editable': True, u'value': u''},
                 u'editable': {u'editable': False, u'value': False},
                 u'entity_type': {u'editable': False, u'value': u'Version'},
                 u'mandatory': {u'editable': False, u'value': False},
                 u'name': {u'editable': True, u'value': u'Open Notes'},
                 u'properties': {u'default_value': {u'editable': False,
                                                    u'value': None},
                                 u'summary_default': {u'editable': True,
                                                      u'value': u'none'},
                                 u'valid_types': {u'editable': True,
                                                  u'value': [u'Note']}}},
 u'open_notes_count': {u'data_type': {u'editable': False, u'value': u'text'},
                       u'description': {u'editable': True, u'value': u''},
                       u'editable': {u'editable': False, u'value': False},
                       u'entity_type': {u'editable': False,
                                        u'value': u'Version'},
                       u'mandatory': {u'editable': False, u'value': False},
                       u'name': {u'editable': True,
                                 u'value': u'Open Notes Count'},
                       u'properties': {u'default_value': {u'editable': False,
                                                          u'value': None},
                                       u'summary_default': {u'editable': True,
                                                            u'value': u'none'}}},
 u'playlists': {u'data_type': {u'editable': False, u'value': u'multi_entity'},
                u'description': {u'editable': True, u'value': u''},
                u'editable': {u'editable': False, u'value': True},
                u'entity_type': {u'editable': False, u'value': u'Version'},
                u'mandatory': {u'editable': False, u'value': False},
                u'name': {u'editable': True, u'value': u'Playlists'},
                u'properties': {u'default_value': {u'editable': False,
                                                   u'value': None},
                                u'summary_default': {u'editable': True,
                                                     u'value': u'none'},
                                u'valid_types': {u'editable': True,
                                                 u'value': [u'Playlist']}}},
 u'project': {u'data_type': {u'editable': False, u'value': u'entity'},
              u'description': {u'editable': True, u'value': u''},
              u'editable': {u'editable': False, u'value': True},
              u'entity_type': {u'editable': False, u'value': u'Version'},
              u'mandatory': {u'editable': False, u'value': False},
              u'name': {u'editable': True, u'value': u'Project'},
              u'properties': {u'default_value': {u'editable': False,
                                                 u'value': None},
                              u'summary_default': {u'editable': True,
                                                   u'value': u'none'},
                              u'valid_types': {u'editable': True,
                                               u'value': [u'Project']}}},
 u'sg_department': {u'data_type': {u'editable': False, u'value': u'text'},
                    u'description': {u'editable': True,
                                     u'value': u'The department the Version was submitted from. This is used to find the latest Version from the same department.'},
                    u'editable': {u'editable': False, u'value': True},
                    u'entity_type': {u'editable': False,
                                     u'value': u'Version'},
                    u'mandatory': {u'editable': False, u'value': False},
                    u'name': {u'editable': True, u'value': u'Department'},
                    u'properties': {u'default_value': {u'editable': False,
                                                       u'value': None},
                                    u'summary_default': {u'editable': True,
                                                         u'value': u'none'}}},
 u'sg_first_frame': {u'data_type': {u'editable': False, u'value': u'number'},
                     u'description': {u'editable': True,
                                      u'value': u'The first frame number contained in the Version. Used in playback of the movie or frames to calculate the first frame available in the Version.'},
                     u'editable': {u'editable': False, u'value': True},
                     u'entity_type': {u'editable': False,
                                      u'value': u'Version'},
                     u'mandatory': {u'editable': False, u'value': False},
                     u'name': {u'editable': True, u'value': u'First Frame'},
                     u'properties': {u'default_value': {u'editable': False,
                                                        u'value': None},
                                     u'summary_default': {u'editable': True,
                                                          u'value': u'none'}}},
 u'sg_frames_aspect_ratio': {u'data_type': {u'editable': False,
                                            u'value': u'float'},
                             u'description': {u'editable': True,
                                              u'value': u'Aspect ratio of the high res frames. Used to format the image correctly for viewing.'},
                             u'editable': {u'editable': False,
                                           u'value': True},
                             u'entity_type': {u'editable': False,
                                              u'value': u'Version'},
                             u'mandatory': {u'editable': False,
                                            u'value': False},
                             u'name': {u'editable': True,
                                       u'value': u'Frames Aspect Ratio'},
                             u'properties': {u'default_value': {u'editable': False,
                                                                u'value': None},
                                             u'summary_default': {u'editable': True,
                                                                  u'value': u'none'}}},
 u'sg_frames_have_slate': {u'data_type': {u'editable': False,
                                          u'value': u'checkbox'},
                           u'description': {u'editable': True,
                                            u'value': u'Indicates whether the frames have a slate or not. This is used to include or omit the slate from playback.'},
                           u'editable': {u'editable': False, u'value': True},
                           u'entity_type': {u'editable': False,
                                            u'value': u'Version'},
                           u'mandatory': {u'editable': False,
                                          u'value': False},
                           u'name': {u'editable': True,
                                     u'value': u'Frames Have Slate'},
                           u'properties': {u'default_value': {u'editable': False,
                                                              u'value': False},
                                           u'summary_default': {u'editable': True,
                                                                u'value': u'none'}}},
 u'sg_last_frame': {u'data_type': {u'editable': False, u'value': u'number'},
                    u'description': {u'editable': True,
                                     u'value': u'The last frame number contained in the Version. Used in playback of the movie or frames to calculate the last frame available in the Version.'},
                    u'editable': {u'editable': False, u'value': True},
                    u'entity_type': {u'editable': False,
                                     u'value': u'Version'},
                    u'mandatory': {u'editable': False, u'value': False},
                    u'name': {u'editable': True, u'value': u'Last Frame'},
                    u'properties': {u'default_value': {u'editable': False,
                                                       u'value': None},
                                    u'summary_default': {u'editable': True,
                                                         u'value': u'none'}}},
 u'sg_movie_aspect_ratio': {u'data_type': {u'editable': False,
                                           u'value': u'float'},
                            u'description': {u'editable': True,
                                             u'value': u'Aspect ratio of the the movie. Used to format the image correctly for viewing.'},
                            u'editable': {u'editable': False, u'value': True},
                            u'entity_type': {u'editable': False,
                                             u'value': u'Version'},
                            u'mandatory': {u'editable': False,
                                           u'value': False},
                            u'name': {u'editable': True,
                                      u'value': u'Movie Aspect Ratio'},
                            u'properties': {u'default_value': {u'editable': False,
                                                               u'value': None},
                                            u'summary_default': {u'editable': True,
                                                                 u'value': u'none'}}},
 u'sg_movie_has_slate': {u'data_type': {u'editable': False,
                                        u'value': u'checkbox'},
                         u'description': {u'editable': True,
                                          u'value': u'Indicates whether the movie file has a slate or not. This is used to include or omit the slate from playback.'},
                         u'editable': {u'editable': False, u'value': True},
                         u'entity_type': {u'editable': False,
                                          u'value': u'Version'},
                         u'mandatory': {u'editable': False, u'value': False},
                         u'name': {u'editable': True,
                                   u'value': u'Movie Has Slate'},
                         u'properties': {u'default_value': {u'editable': False,
                                                            u'value': False},
                                         u'summary_default': {u'editable': True,
                                                              u'value': u'none'}}},
 u'sg_path_to_frames': {u'data_type': {u'editable': False, u'value': u'text'},
                        u'description': {u'editable': True,
                                         u'value': u'Location of the high res frames on your local filesystem. Used for playback of high resolution frames.'},
                        u'editable': {u'editable': False, u'value': True},
                        u'entity_type': {u'editable': False,
                                         u'value': u'Version'},
                        u'mandatory': {u'editable': False, u'value': False},
                        u'name': {u'editable': True,
                                  u'value': u'Path to Frames'},
                        u'properties': {u'default_value': {u'editable': False,
                                                           u'value': None},
                                        u'summary_default': {u'editable': True,
                                                             u'value': u'none'}}},
 u'sg_path_to_movie': {u'data_type': {u'editable': False, u'value': u'text'},
                       u'description': {u'editable': True,
                                        u'value': u'Location of the movie on your local filesystem (not uploaded). Used for playback of lower resolution movie media stored locally.'},
                       u'editable': {u'editable': False, u'value': True},
                       u'entity_type': {u'editable': False,
                                        u'value': u'Version'},
                       u'mandatory': {u'editable': False, u'value': False},
                       u'name': {u'editable': True,
                                 u'value': u'Path to Movie'},
                       u'properties': {u'default_value': {u'editable': False,
                                                          u'value': None},
                                       u'summary_default': {u'editable': True,
                                                            u'value': u'none'}}},
 u'sg_status_list': {u'data_type': {u'editable': False,
                                    u'value': u'status_list'},
                     u'description': {u'editable': True, u'value': u''},
                     u'editable': {u'editable': False, u'value': True},
                     u'entity_type': {u'editable': False,
                                      u'value': u'Version'},
                     u'mandatory': {u'editable': False, u'value': False},
                     u'name': {u'editable': True, u'value': u'Status'},
                     u'properties': {u'default_value': {u'editable': True,
                                                        u'value': u'rev'},
                                     u'summary_default': {u'editable': True,
                                                          u'value': u'status_list'},
                                     u'valid_values': {u'editable': True,
                                                       u'value': [u'na',
                                                                  u'rev',
                                                                  u'vwd']}}},
 u'sg_task': {u'data_type': {u'editable': False, u'value': u'entity'},
              u'description': {u'editable': True, u'value': u''},
              u'editable': {u'editable': False, u'value': True},
              u'entity_type': {u'editable': False, u'value': u'Version'},
              u'mandatory': {u'editable': False, u'value': False},
              u'name': {u'editable': True, u'value': u'Task'},
              u'properties': {u'default_value': {u'editable': False,
                                                 u'value': None},
                              u'summary_default': {u'editable': True,
                                                   u'value': u'none'},
                              u'valid_types': {u'editable': True,
                                               u'value': [u'Task']}}},
 u'sg_uploaded_movie': {u'data_type': {u'editable': False, u'value': u'url'},
                        u'description': {u'editable': True,
                                         u'value': u'File field to contain the uploaded movie file. Used for playback of lower resolution movie media stored in Shotgun.'},
                        u'editable': {u'editable': False, u'value': True},
                        u'entity_type': {u'editable': False,
                                         u'value': u'Version'},
                        u'mandatory': {u'editable': False, u'value': False},
                        u'name': {u'editable': True,
                                  u'value': u'Uploaded Movie'},
                        u'properties': {u'default_value': {u'editable': False,
                                                           u'value': None},
                                        u'open_in_new_window': {u'editable': True,
                                                                u'value': True},
                                        u'summary_default': {u'editable': True,
                                                             u'value': u'none'}}},
 u'sg_version_type': {u'data_type': {u'editable': False, u'value': u'list'},
                      u'description': {u'editable': True, u'value': u''},
                      u'editable': {u'editable': False, u'value': True},
                      u'entity_type': {u'editable': False,
                                       u'value': u'Version'},
                      u'mandatory': {u'editable': False, u'value': False},
                      u'name': {u'editable': True, u'value': u'Type'},
                      u'properties': {u'default_value': {u'editable': False,
                                                         u'value': None},
                                      u'summary_default': {u'editable': True,
                                                           u'value': u'none'},
                                      u'valid_values': {u'editable': True,
                                                        u'value': []}}},
 u'step_0': {u'data_type': {u'editable': False, u'value': u'pivot_column'},
             u'description': {u'editable': True, u'value': u''},
             u'editable': {u'editable': False, u'value': False},
             u'entity_type': {u'editable': False, u'value': u'Version'},
             u'mandatory': {u'editable': False, u'value': False},
             u'name': {u'editable': True, u'value': u'ALL TASKS'},
             u'properties': {u'default_value': {u'editable': False,
                                                u'value': None},
                             u'summary_default': {u'editable': False,
                                                  u'value': u'none'}}},
 u'tag_list': {u'data_type': {u'editable': False, u'value': u'tag_list'},
               u'description': {u'editable': True, u'value': u''},
               u'editable': {u'editable': False, u'value': True},
               u'entity_type': {u'editable': False, u'value': u'Version'},
               u'mandatory': {u'editable': False, u'value': False},
               u'name': {u'editable': True, u'value': u'Tags'},
               u'properties': {u'default_value': {u'editable': False,
                                                  u'value': None},
                               u'summary_default': {u'editable': True,
                                                    u'value': u'none'},
                               u'valid_types': {u'editable': True,
                                                u'value': [u'Tag']}}},
 u'task_template': {u'data_type': {u'editable': False, u'value': u'entity'},
                    u'description': {u'editable': True, u'value': u''},
                    u'editable': {u'editable': False, u'value': True},
                    u'entity_type': {u'editable': False,
                                     u'value': u'Version'},
                    u'mandatory': {u'editable': False, u'value': False},
                    u'name': {u'editable': True, u'value': u'Task Template'},
                    u'properties': {u'default_value': {u'editable': False,
                                                       u'value': None},
                                    u'summary_default': {u'editable': True,
                                                         u'value': u'none'},
                                    u'valid_types': {u'editable': True,
                                                     u'value': [u'TaskTemplate']}}},
 u'tasks': {u'data_type': {u'editable': False, u'value': u'multi_entity'},
            u'description': {u'editable': True, u'value': u''},
            u'editable': {u'editable': False, u'value': True},
            u'entity_type': {u'editable': False, u'value': u'Version'},
            u'mandatory': {u'editable': False, u'value': False},
            u'name': {u'editable': True, u'value': u'Tasks'},
            u'properties': {u'default_value': {u'editable': False,
                                               u'value': None},
                            u'summary_default': {u'editable': True,
                                                 u'value': u'none'},
                            u'valid_types': {u'editable': True,
                                             u'value': [u'Task']}}},
 u'updated_at': {u'data_type': {u'editable': False, u'value': u'date_time'},
                 u'description': {u'editable': True, u'value': u''},
                 u'editable': {u'editable': False, u'value': False},
                 u'entity_type': {u'editable': False, u'value': u'Version'},
                 u'mandatory': {u'editable': False, u'value': False},
                 u'name': {u'editable': True, u'value': u'Date Updated'},
                 u'properties': {u'default_value': {u'editable': False,
                                                    u'value': None},
                                 u'summary_default': {u'editable': True,
                                                      u'value': u'none'}}},
 u'updated_by': {u'data_type': {u'editable': False, u'value': u'entity'},
                 u'description': {u'editable': True, u'value': u''},
                 u'editable': {u'editable': False, u'value': False},
                 u'entity_type': {u'editable': False, u'value': u'Version'},
                 u'mandatory': {u'editable': False, u'value': False},
                 u'name': {u'editable': True, u'value': u'Updated by'},
                 u'properties': {u'default_value': {u'editable': False,
                                                    u'value': None},
                                 u'summary_default': {u'editable': True,
                                                      u'value': u'none'},
                                 u'valid_types': {u'editable': True,
                                                  u'value': [u'HumanUser',
                                                             u'ApiUser']}}},
 u'user': {u'data_type': {u'editable': False, u'value': u'entity'},
           u'description': {u'editable': True, u'value': u''},
           u'editable': {u'editable': False, u'value': True},
           u'entity_type': {u'editable': False, u'value': u'Version'},
           u'mandatory': {u'editable': False, u'value': False},
           u'name': {u'editable': True, u'value': u'Artist'},
           u'properties': {u'default_value': {u'editable': False,
                                              u'value': None},
                           u'summary_default': {u'editable': True,
                                                u'value': u'none'},
                           u'valid_types': {u'editable': True,
                                            u'value': [u'HumanUser',
                                                       u'ApiUser']}}}
}}








schema_field_read_version = {u'code': {u'data_type': {u'editable': False, u'value': u'text'},
           u'description': {u'editable': True, u'value': u''},
           u'editable': {u'editable': False, u'value': True},
           u'entity_type': {u'editable': False, u'value': u'Version'},
           u'mandatory': {u'editable': False, u'value': True},
           u'name': {u'editable': True, u'value': u'Version Name'},
           u'properties': {u'default_value': {u'editable': False,
                                              u'value': None},
                           u'summary_default': {u'editable': True,
                                                u'value': u'none'}}},
 u'created_at': {u'data_type': {u'editable': False, u'value': u'date_time'},
                 u'description': {u'editable': True, u'value': u''},
                 u'editable': {u'editable': False, u'value': False},
                 u'entity_type': {u'editable': False, u'value': u'Version'},
                 u'mandatory': {u'editable': False, u'value': False},
                 u'name': {u'editable': True, u'value': u'Date Created'},
                 u'properties': {u'default_value': {u'editable': False,
                                                    u'value': None},
                                 u'summary_default': {u'editable': True,
                                                      u'value': u'none'}}},
 u'created_by': {u'data_type': {u'editable': False, u'value': u'entity'},
                 u'description': {u'editable': True, u'value': u''},
                 u'editable': {u'editable': False, u'value': False},
                 u'entity_type': {u'editable': False, u'value': u'Version'},
                 u'mandatory': {u'editable': False, u'value': False},
                 u'name': {u'editable': True, u'value': u'Created by'},
                 u'properties': {u'default_value': {u'editable': False,
                                                    u'value': None},
                                 u'summary_default': {u'editable': True,
                                                      u'value': u'none'},
                                 u'valid_types': {u'editable': True,
                                                  u'value': [u'HumanUser',
                                                             u'ApiUser']}}},
 u'description': {u'data_type': {u'editable': False, u'value': u'text'},
                  u'description': {u'editable': True, u'value': u''},
                  u'editable': {u'editable': False, u'value': True},
                  u'entity_type': {u'editable': False, u'value': u'Version'},
                  u'mandatory': {u'editable': False, u'value': False},
                  u'name': {u'editable': True, u'value': u'Description'},
                  u'properties': {u'default_value': {u'editable': False,
                                                     u'value': None},
                                  u'summary_default': {u'editable': True,
                                                       u'value': u'none'}}},
 u'entity': {u'data_type': {u'editable': False, u'value': u'entity'},
             u'description': {u'editable': True, u'value': u''},
             u'editable': {u'editable': False, u'value': True},
             u'entity_type': {u'editable': False, u'value': u'Version'},
             u'mandatory': {u'editable': False, u'value': False},
             u'name': {u'editable': True, u'value': u'Link'},
             u'properties': {u'default_value': {u'editable': False,
                                                u'value': None},
                             u'summary_default': {u'editable': True,
                                                  u'value': u'none'},
                             u'valid_types': {u'editable': True,
                                              u'value': [u'Asset',
                                                         u'Scene',
                                                         u'Sequence',
                                                         u'Shot']}}},
 u'frame_count': {u'data_type': {u'editable': False, u'value': u'number'},
                  u'description': {u'editable': True, u'value': u''},
                  u'editable': {u'editable': False, u'value': True},
                  u'entity_type': {u'editable': False, u'value': u'Version'},
                  u'mandatory': {u'editable': False, u'value': False},
                  u'name': {u'editable': True, u'value': u'Frame Count'},
                  u'properties': {u'default_value': {u'editable': False,
                                                     u'value': None},
                                  u'summary_default': {u'editable': True,
                                                       u'value': u'none'}}},
 u'frame_range': {u'data_type': {u'editable': False, u'value': u'text'},
                  u'description': {u'editable': True, u'value': u''},
                  u'editable': {u'editable': False, u'value': True},
                  u'entity_type': {u'editable': False, u'value': u'Version'},
                  u'mandatory': {u'editable': False, u'value': False},
                  u'name': {u'editable': True, u'value': u'Frame Range'},
                  u'properties': {u'default_value': {u'editable': False,
                                                     u'value': None},
                                  u'summary_default': {u'editable': True,
                                                       u'value': u'none'}}},
 u'id': {u'data_type': {u'editable': False, u'value': u'number'},
         u'description': {u'editable': True, u'value': u''},
         u'editable': {u'editable': False, u'value': False},
         u'entity_type': {u'editable': False, u'value': u'Version'},
         u'mandatory': {u'editable': False, u'value': False},
         u'name': {u'editable': True, u'value': u'Id'},
         u'properties': {u'default_value': {u'editable': False,
                                            u'value': None},
                         u'summary_default': {u'editable': True,
                                              u'value': u'none'}}},
 u'image': {u'data_type': {u'editable': False, u'value': u'image'},
            u'description': {u'editable': True, u'value': u''},
            u'editable': {u'editable': False, u'value': True},
            u'entity_type': {u'editable': False, u'value': u'Version'},
            u'mandatory': {u'editable': False, u'value': False},
            u'name': {u'editable': True, u'value': u'Thumbnail'},
            u'properties': {u'default_value': {u'editable': False,
                                               u'value': None},
                            u'summary_default': {u'editable': True,
                                                 u'value': u'none'}}},
 u'notes': {u'data_type': {u'editable': False, u'value': u'multi_entity'},
            u'description': {u'editable': True, u'value': u''},
            u'editable': {u'editable': False, u'value': True},
            u'entity_type': {u'editable': False, u'value': u'Version'},
            u'mandatory': {u'editable': False, u'value': False},
            u'name': {u'editable': True, u'value': u'Notes'},
            u'properties': {u'default_value': {u'editable': False,
                                               u'value': None},
                            u'summary_default': {u'editable': True,
                                                 u'value': u'none'},
                            u'valid_types': {u'editable': True,
                                             u'value': [u'Note']}}},
 u'open_notes': {u'data_type': {u'editable': False,
                                u'value': u'multi_entity'},
                 u'description': {u'editable': True, u'value': u''},
                 u'editable': {u'editable': False, u'value': False},
                 u'entity_type': {u'editable': False, u'value': u'Version'},
                 u'mandatory': {u'editable': False, u'value': False},
                 u'name': {u'editable': True, u'value': u'Open Notes'},
                 u'properties': {u'default_value': {u'editable': False,
                                                    u'value': None},
                                 u'summary_default': {u'editable': True,
                                                      u'value': u'none'},
                                 u'valid_types': {u'editable': True,
                                                  u'value': [u'Note']}}},
 u'open_notes_count': {u'data_type': {u'editable': False, u'value': u'text'},
                       u'description': {u'editable': True, u'value': u''},
                       u'editable': {u'editable': False, u'value': False},
                       u'entity_type': {u'editable': False,
                                        u'value': u'Version'},
                       u'mandatory': {u'editable': False, u'value': False},
                       u'name': {u'editable': True,
                                 u'value': u'Open Notes Count'},
                       u'properties': {u'default_value': {u'editable': False,
                                                          u'value': None},
                                       u'summary_default': {u'editable': True,
                                                            u'value': u'none'}}},
 u'playlists': {u'data_type': {u'editable': False, u'value': u'multi_entity'},
                u'description': {u'editable': True, u'value': u''},
                u'editable': {u'editable': False, u'value': True},
                u'entity_type': {u'editable': False, u'value': u'Version'},
                u'mandatory': {u'editable': False, u'value': False},
                u'name': {u'editable': True, u'value': u'Playlists'},
                u'properties': {u'default_value': {u'editable': False,
                                                   u'value': None},
                                u'summary_default': {u'editable': True,
                                                     u'value': u'none'},
                                u'valid_types': {u'editable': True,
                                                 u'value': [u'Playlist']}}},
 u'project': {u'data_type': {u'editable': False, u'value': u'entity'},
              u'description': {u'editable': True, u'value': u''},
              u'editable': {u'editable': False, u'value': True},
              u'entity_type': {u'editable': False, u'value': u'Version'},
              u'mandatory': {u'editable': False, u'value': False},
              u'name': {u'editable': True, u'value': u'Project'},
              u'properties': {u'default_value': {u'editable': False,
                                                 u'value': None},
                              u'summary_default': {u'editable': True,
                                                   u'value': u'none'},
                              u'valid_types': {u'editable': True,
                                               u'value': [u'Project']}}},
 u'sg_department': {u'data_type': {u'editable': False, u'value': u'text'},
                    u'description': {u'editable': True,
                                     u'value': u'The department the Version was submitted from. This is used to find the latest Version from the same department.'},
                    u'editable': {u'editable': False, u'value': True},
                    u'entity_type': {u'editable': False,
                                     u'value': u'Version'},
                    u'mandatory': {u'editable': False, u'value': False},
                    u'name': {u'editable': True, u'value': u'Department'},
                    u'properties': {u'default_value': {u'editable': False,
                                                       u'value': None},
                                    u'summary_default': {u'editable': True,
                                                         u'value': u'none'}}},
 u'sg_first_frame': {u'data_type': {u'editable': False, u'value': u'number'},
                     u'description': {u'editable': True,
                                      u'value': u'The first frame number contained in the Version. Used in playback of the movie or frames to calculate the first frame available in the Version.'},
                     u'editable': {u'editable': False, u'value': True},
                     u'entity_type': {u'editable': False,
                                      u'value': u'Version'},
                     u'mandatory': {u'editable': False, u'value': False},
                     u'name': {u'editable': True, u'value': u'First Frame'},
                     u'properties': {u'default_value': {u'editable': False,
                                                        u'value': None},
                                     u'summary_default': {u'editable': True,
                                                          u'value': u'none'}}},
 u'sg_frames_aspect_ratio': {u'data_type': {u'editable': False,
                                            u'value': u'float'},
                             u'description': {u'editable': True,
                                              u'value': u'Aspect ratio of the high res frames. Used to format the image correctly for viewing.'},
                             u'editable': {u'editable': False,
                                           u'value': True},
                             u'entity_type': {u'editable': False,
                                              u'value': u'Version'},
                             u'mandatory': {u'editable': False,
                                            u'value': False},
                             u'name': {u'editable': True,
                                       u'value': u'Frames Aspect Ratio'},
                             u'properties': {u'default_value': {u'editable': False,
                                                                u'value': None},
                                             u'summary_default': {u'editable': True,
                                                                  u'value': u'none'}}},
 u'sg_frames_have_slate': {u'data_type': {u'editable': False,
                                          u'value': u'checkbox'},
                           u'description': {u'editable': True,
                                            u'value': u'Indicates whether the frames have a slate or not. This is used to include or omit the slate from playback.'},
                           u'editable': {u'editable': False, u'value': True},
                           u'entity_type': {u'editable': False,
                                            u'value': u'Version'},
                           u'mandatory': {u'editable': False,
                                          u'value': False},
                           u'name': {u'editable': True,
                                     u'value': u'Frames Have Slate'},
                           u'properties': {u'default_value': {u'editable': False,
                                                              u'value': False},
                                           u'summary_default': {u'editable': True,
                                                                u'value': u'none'}}},
 u'sg_last_frame': {u'data_type': {u'editable': False, u'value': u'number'},
                    u'description': {u'editable': True,
                                     u'value': u'The last frame number contained in the Version. Used in playback of the movie or frames to calculate the last frame available in the Version.'},
                    u'editable': {u'editable': False, u'value': True},
                    u'entity_type': {u'editable': False,
                                     u'value': u'Version'},
                    u'mandatory': {u'editable': False, u'value': False},
                    u'name': {u'editable': True, u'value': u'Last Frame'},
                    u'properties': {u'default_value': {u'editable': False,
                                                       u'value': None},
                                    u'summary_default': {u'editable': True,
                                                         u'value': u'none'}}},
 u'sg_movie_aspect_ratio': {u'data_type': {u'editable': False,
                                           u'value': u'float'},
                            u'description': {u'editable': True,
                                             u'value': u'Aspect ratio of the the movie. Used to format the image correctly for viewing.'},
                            u'editable': {u'editable': False, u'value': True},
                            u'entity_type': {u'editable': False,
                                             u'value': u'Version'},
                            u'mandatory': {u'editable': False,
                                           u'value': False},
                            u'name': {u'editable': True,
                                      u'value': u'Movie Aspect Ratio'},
                            u'properties': {u'default_value': {u'editable': False,
                                                               u'value': None},
                                            u'summary_default': {u'editable': True,
                                                                 u'value': u'none'}}},
 u'sg_movie_has_slate': {u'data_type': {u'editable': False,
                                        u'value': u'checkbox'},
                         u'description': {u'editable': True,
                                          u'value': u'Indicates whether the movie file has a slate or not. This is used to include or omit the slate from playback.'},
                         u'editable': {u'editable': False, u'value': True},
                         u'entity_type': {u'editable': False,
                                          u'value': u'Version'},
                         u'mandatory': {u'editable': False, u'value': False},
                         u'name': {u'editable': True,
                                   u'value': u'Movie Has Slate'},
                         u'properties': {u'default_value': {u'editable': False,
                                                            u'value': False},
                                         u'summary_default': {u'editable': True,
                                                              u'value': u'none'}}},
 u'sg_path_to_frames': {u'data_type': {u'editable': False, u'value': u'text'},
                        u'description': {u'editable': True,
                                         u'value': u'Location of the high res frames on your local filesystem. Used for playback of high resolution frames.'},
                        u'editable': {u'editable': False, u'value': True},
                        u'entity_type': {u'editable': False,
                                         u'value': u'Version'},
                        u'mandatory': {u'editable': False, u'value': False},
                        u'name': {u'editable': True,
                                  u'value': u'Path to Frames'},
                        u'properties': {u'default_value': {u'editable': False,
                                                           u'value': None},
                                        u'summary_default': {u'editable': True,
                                                             u'value': u'none'}}},
 u'sg_path_to_movie': {u'data_type': {u'editable': False, u'value': u'text'},
                       u'description': {u'editable': True,
                                        u'value': u'Location of the movie on your local filesystem (not uploaded). Used for playback of lower resolution movie media stored locally.'},
                       u'editable': {u'editable': False, u'value': True},
                       u'entity_type': {u'editable': False,
                                        u'value': u'Version'},
                       u'mandatory': {u'editable': False, u'value': False},
                       u'name': {u'editable': True,
                                 u'value': u'Path to Movie'},
                       u'properties': {u'default_value': {u'editable': False,
                                                          u'value': None},
                                       u'summary_default': {u'editable': True,
                                                            u'value': u'none'}}},
 u'sg_status_list': {u'data_type': {u'editable': False,
                                    u'value': u'status_list'},
                     u'description': {u'editable': True, u'value': u''},
                     u'editable': {u'editable': False, u'value': True},
                     u'entity_type': {u'editable': False,
                                      u'value': u'Version'},
                     u'mandatory': {u'editable': False, u'value': False},
                     u'name': {u'editable': True, u'value': u'Status'},
                     u'properties': {u'default_value': {u'editable': True,
                                                        u'value': u'rev'},
                                     u'summary_default': {u'editable': True,
                                                          u'value': u'status_list'},
                                     u'valid_values': {u'editable': True,
                                                       u'value': [u'na',
                                                                  u'rev',
                                                                  u'vwd']}}},
 u'sg_task': {u'data_type': {u'editable': False, u'value': u'entity'},
              u'description': {u'editable': True, u'value': u''},
              u'editable': {u'editable': False, u'value': True},
              u'entity_type': {u'editable': False, u'value': u'Version'},
              u'mandatory': {u'editable': False, u'value': False},
              u'name': {u'editable': True, u'value': u'Task'},
              u'properties': {u'default_value': {u'editable': False,
                                                 u'value': None},
                              u'summary_default': {u'editable': True,
                                                   u'value': u'none'},
                              u'valid_types': {u'editable': True,
                                               u'value': [u'Task']}}},
 u'sg_uploaded_movie': {u'data_type': {u'editable': False, u'value': u'url'},
                        u'description': {u'editable': True,
                                         u'value': u'File field to contain the uploaded movie file. Used for playback of lower resolution movie media stored in Shotgun.'},
                        u'editable': {u'editable': False, u'value': True},
                        u'entity_type': {u'editable': False,
                                         u'value': u'Version'},
                        u'mandatory': {u'editable': False, u'value': False},
                        u'name': {u'editable': True,
                                  u'value': u'Uploaded Movie'},
                        u'properties': {u'default_value': {u'editable': False,
                                                           u'value': None},
                                        u'open_in_new_window': {u'editable': True,
                                                                u'value': True},
                                        u'summary_default': {u'editable': True,
                                                             u'value': u'none'}}},
 u'sg_version_type': {u'data_type': {u'editable': False, u'value': u'list'},
                      u'description': {u'editable': True, u'value': u''},
                      u'editable': {u'editable': False, u'value': True},
                      u'entity_type': {u'editable': False,
                                       u'value': u'Version'},
                      u'mandatory': {u'editable': False, u'value': False},
                      u'name': {u'editable': True, u'value': u'Type'},
                      u'properties': {u'default_value': {u'editable': False,
                                                         u'value': None},
                                      u'summary_default': {u'editable': True,
                                                           u'value': u'none'},
                                      u'valid_values': {u'editable': True,
                                                        u'value': []}}},
 u'step_0': {u'data_type': {u'editable': False, u'value': u'pivot_column'},
             u'description': {u'editable': True, u'value': u''},
             u'editable': {u'editable': False, u'value': False},
             u'entity_type': {u'editable': False, u'value': u'Version'},
             u'mandatory': {u'editable': False, u'value': False},
             u'name': {u'editable': True, u'value': u'ALL TASKS'},
             u'properties': {u'default_value': {u'editable': False,
                                                u'value': None},
                             u'summary_default': {u'editable': False,
                                                  u'value': u'none'}}},
 u'tag_list': {u'data_type': {u'editable': False, u'value': u'tag_list'},
               u'description': {u'editable': True, u'value': u''},
               u'editable': {u'editable': False, u'value': True},
               u'entity_type': {u'editable': False, u'value': u'Version'},
               u'mandatory': {u'editable': False, u'value': False},
               u'name': {u'editable': True, u'value': u'Tags'},
               u'properties': {u'default_value': {u'editable': False,
                                                  u'value': None},
                               u'summary_default': {u'editable': True,
                                                    u'value': u'none'},
                               u'valid_types': {u'editable': True,
                                                u'value': [u'Tag']}}},
 u'task_template': {u'data_type': {u'editable': False, u'value': u'entity'},
                    u'description': {u'editable': True, u'value': u''},
                    u'editable': {u'editable': False, u'value': True},
                    u'entity_type': {u'editable': False,
                                     u'value': u'Version'},
                    u'mandatory': {u'editable': False, u'value': False},
                    u'name': {u'editable': True, u'value': u'Task Template'},
                    u'properties': {u'default_value': {u'editable': False,
                                                       u'value': None},
                                    u'summary_default': {u'editable': True,
                                                         u'value': u'none'},
                                    u'valid_types': {u'editable': True,
                                                     u'value': [u'TaskTemplate']}}},
 u'tasks': {u'data_type': {u'editable': False, u'value': u'multi_entity'},
            u'description': {u'editable': True, u'value': u''},
            u'editable': {u'editable': False, u'value': True},
            u'entity_type': {u'editable': False, u'value': u'Version'},
            u'mandatory': {u'editable': False, u'value': False},
            u'name': {u'editable': True, u'value': u'Tasks'},
            u'properties': {u'default_value': {u'editable': False,
                                               u'value': None},
                            u'summary_default': {u'editable': True,
                                                 u'value': u'none'},
                            u'valid_types': {u'editable': True,
                                             u'value': [u'Task']}}},
 u'updated_at': {u'data_type': {u'editable': False, u'value': u'date_time'},
                 u'description': {u'editable': True, u'value': u''},
                 u'editable': {u'editable': False, u'value': False},
                 u'entity_type': {u'editable': False, u'value': u'Version'},
                 u'mandatory': {u'editable': False, u'value': False},
                 u'name': {u'editable': True, u'value': u'Date Updated'},
                 u'properties': {u'default_value': {u'editable': False,
                                                    u'value': None},
                                 u'summary_default': {u'editable': True,
                                                      u'value': u'none'}}},
 u'updated_by': {u'data_type': {u'editable': False, u'value': u'entity'},
                 u'description': {u'editable': True, u'value': u''},
                 u'editable': {u'editable': False, u'value': False},
                 u'entity_type': {u'editable': False, u'value': u'Version'},
                 u'mandatory': {u'editable': False, u'value': False},
                 u'name': {u'editable': True, u'value': u'Updated by'},
                 u'properties': {u'default_value': {u'editable': False,
                                                    u'value': None},
                                 u'summary_default': {u'editable': True,
                                                      u'value': u'none'},
                                 u'valid_types': {u'editable': True,
                                                  u'value': [u'HumanUser',
                                                             u'ApiUser']}}},
 u'user': {u'data_type': {u'editable': False, u'value': u'entity'},
           u'description': {u'editable': True, u'value': u''},
           u'editable': {u'editable': False, u'value': True},
           u'entity_type': {u'editable': False, u'value': u'Version'},
           u'mandatory': {u'editable': False, u'value': False},
           u'name': {u'editable': True, u'value': u'Artist'},
           u'properties': {u'default_value': {u'editable': False,
                                              u'value': None},
                           u'summary_default': {u'editable': True,
                                                u'value': u'none'},
                           u'valid_types': {u'editable': True,
                                            u'value': [u'HumanUser',
                                                       u'ApiUser']}}}}





schema_field_read_version_user = {u'user': {u'data_type': {u'editable': False, u'value': u'entity'},
           u'description': {u'editable': True, u'value': u''},
           u'editable': {u'editable': False, u'value': True},
           u'entity_type': {u'editable': False, u'value': u'Version'},
           u'mandatory': {u'editable': False, u'value': False},
           u'name': {u'editable': True, u'value': u'Artist'},
           u'properties': {u'default_value': {u'editable': False,
                                              u'value': None},
                           u'summary_default': {u'editable': True,
                                                u'value': u'none'},
                           u'valid_types': {u'editable': True,
                                            u'value': [u'HumanUser',
                                                       u'ApiUser']}}}}
                                                       